### ISSUE TITLE
Does playground work?

### ISSUE THREAD

**Issue by clouds56** [nil/v-drag#20]

**Comment by thundree** [comment]
Just came from the website, the demo/playground does not work at all.
Might be worthy look into it soon, I guess?

**Comment by nil** [comment]
Playground was part of the website I had planned for v-drag. Development was abandoned quite some time ago, and now I'm back at it. But as the new website/documentation will be much simpler, playground won't be added. Instead, live demos will appear next to code examples.

Maybe sometime in the future I will start working on it again.
