### ISSUE TITLE
Package.json points to non-existing files. Dependency not found

### ISSUE THREAD

**Issue by Markussss** [nil/v-drag#32]
The recent update, where the `dist`-directories were removed from version control, broke usage of `v-drag`, because `package.json` is still pointing to the `dist`-directories.

This leads to a hard to debug error message, such as:

```
ERROR  Failed to compile with 1 errors1:18:18 PM

This dependency was not found:

* v-drag in ./src/app.js

To install it, you can run: npm install --save v-drag
```

I would suggest that you either run the build steps and add the `dist`-directory back to git.

**Comment by nil** [comment]
Should be fixed right now. Thanks for pointing it out :)

**Comment by Markussss** [comment]
Nice! :smile: Will try it out tomorrow!

**Comment by Markussss** [comment]
Works very nicely now! Thank you for helping! :smile:
