### ISSUE TITLE
Error reported in updatedHook function

### ISSUE THREAD

**Issue by strting** [nil/v-drag#35]
![image](https://user-images.githubusercontent.com/26641698/177754175-2d994c9d-adb9-43bf-8fde-4b92a9160c45.png)
![image](https://user-images.githubusercontent.com/26641698/177754458-9d0402e7-e513-4c96-9cfe-9798ca1ce32e.png)
binding.oldValue may be undefined

**Comment by nil** [comment]
Can you share some code to replicate it?

**Comment by qq1871508593** [comment]
#37

**Comment by nil** [comment]
Closing this issue as it's fixed with the latest commit
