### ISSUE TITLE
@v-drag-start doesn't work.

### ISSUE THREAD

**Issue by gw128** [nil/v-drag#42]
@v-drag-start event doesn't work.  @v-drag-down works instead.
Probably a bug in documentation or in file dragStart.js 
vueDragEvent(moveElement, 'down');

**Comment by mahu032** [comment]
you can use event like  @v-drag-[xxx].native 

because  source code write  el.dispatchEvent(new Event(`v-drag-${action}`))

**Comment by nil** [comment]
Fixed on v3.0.9

Now both `@v-drag-down` and `@v-drag-start` work.
