### ISSUE TITLE
Browser compatibility issue - Internet Explorer

### ISSUE THREAD

**Issue by arthurmcgregor** [nil/v-drag#5]
Hi, this certainly is the simplest way to integrate dragging with VueJS :-) except I can't get it to work in IE :-( I am using Vue CLI 3 with Babel and Webpack. 

Without making any changes, IE throws an error `SCRIPT1006: Expected ')'`

If I add v-drag to the transpileDependecies list, then it loads the app but when I try to access a component that has v-drag enabled, both Chrome and IE throw a `[Vue warn]: Failed to resolve directive: drag`

I tried forking the repository and fixing the default parameters in `/src/utils/eventListener.js` as I think that may be the problem, but that didn't fix things either.

Any help appreciated!

**Comment by nil** [comment]
The error `[Vue warn]: Failed to resolve directive: drag` is shown because v-drag isn't properly imported. Make sure you have this code:

````vue
import Vue from 'vue'
import vdrag from 'v-drag'

Vue.use(vdrag); // this is the important part
````

I recommend importing it into the root file (normally `main.js`) as it's the only file where Vue is mandatory to be imported, but this code can be in any file you are planning to use v-drag.

**Comment by nil** [comment]
Regarding IE, adapting the script for it would mean change a lot of code as v-drag is built using ES6, something that every major browser supports except Internet Explorer. I could, however, find something like Babel to compile the ES6 code to ES5. If this works (right now I can't make it work) it would add support to IE 11, 10 and maybe 9. Vue doesn't support IE8.

I'll keep you updated.

**Comment by arthurmcgregor** [comment]
Thanks for the reply. We've shifted to another drag library so not needed for us anymore.
