### ISSUE TITLE
Limit drag range

### ISSUE THREAD

**Issue by ratracegrad** [nil/v-drag#7]
Is it possible to limit the height of the drag area? I want to have a drawer that is 500px at bottom of screen. I want people to only drag within this parent container. Now it allows users to drag anywhere on the screen.

**Comment by nil** [comment]
This option isn't available right now, though I have been wanting to add this option to v-drag for quite some time. Currently, you can work arround with the paramters you can get with `window.data`. The keys that you might found interesting are:

- `grab`: the element used to move the draggable element.
- `mouseX` and `mouseY`: return the current mouse position.
- `initialX` and `initialY`: get the inital position of the draggable element.
- `relativeX` and `relativeY`: return the distance between the current and the initial position.

Until the feature you are asking is added, you can code something yourself with `windows.grab.addEventListener('mousemove', ...)`. Sorry for the inconvinience.
